### ISSUE TITLE
What does fp mean ?

### ISSUE THREAD

**Issue by arobase-che** [Miaxos/fp-rust#1]
Functional Programing ?

Shouldn't you wait the Functor trait to be standard ?

**Comment by Miaxos** [comment]
Hello @arobase-che ! Nice to see you here ! ;-)

Fp means Functional Programing.
Well, it would be better if we had the standard Functor trait, but for this we also need the standard HKT implementation in rust. We don't know when it'll be in the rust language.

Here is an attempt to test a point-free implementation of the popular patterns and abstractions available in functional languages. As it's only an attempt right now, I won't wait for the Functor trait.
